name: Publish to crates.io

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p kand
